default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  user: postgres
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: talenses_opportunity_development

test:
  <<: *default
  database: talenses_opportunity_test

production:
  <<: *default
  database: talenses_opportunity_production
  username: talenses_opportunity
  password: <%= ENV["TALENSES_OPPORTUNITY_DATABASE_PASSWORD"] %>
